--ESERCIZI

--UNUSED:
--ALTER TABLE EMP SET UNUSED(DEPT_ID);

--DROP UNUSED:
--ALTER TABLE EMP DROP UNUSED COLUMNS;

--ESERCIZIO 8)
--CREATE THE EMPLOYEES2 TABLE
--INCLUDE ONLY EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID COLUMNS FROM MY_EMPLOYEE

CREATE TABLE EMPLOYEES AS
	SELECT employee_id AS id,
		FIRST_NAME,
		LAST_NAME,
		salary,
		DEPARTMENT_ID AS DEPT_ID
	FROM hr.EMPLOYEES;
	
--ESERCIZIO
--ONLY READ
ALTER TABLE EMPLOYEES READ only; 

--ELIMINARE TUTTE LE RIGHE
DELETE FROM EMPLOYEES;

--UPDATE
UPDATE EMPLOYEES
SET FIRST_NAME = 'Tom'
WHERE id = 100;

SELECT * FROM EMPLOYEES WHERE id = 100;

SELECT count(rowid) FROM EMPLOYEES;

--drop
DROP TABLE dept;




