SELECT employee_id, last_name, job_id, to_char(hire_date) AS "STARDATE"
FROM EMPLOYEES
ORDER BY employee_id;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES
ORDER BY 1;

SELECT to_char(employee_id) AS "Emp#", last_name AS "Employee", job_id AS "Job", HIRE_DATE AS "Hire Date"
FROM EMPLOYEES
ORDER BY employee_id;

SELECT (LAST_NAME || ', ' || JOB_ID) AS "Employee and Title"
FROM EMPLOYEES
ORDER BY LAST_NAME

SELECT (EMPLOYEE_ID || ', ' || FIRST_NAME || ', ' || LAST_NAME || ', ' || PHONE_NUMBER || ', ' || JOB_ID) AS "THE OUTPUT"
FROM EMPLOYEES
ORDER BY LAST_NAME

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000
ORDER BY SALARY DESC

SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000 OR SALARY < 5000
ORDER BY 1;

SELECT FIRST_NAME, LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE LAST_NAME = 'Matos'
OR LAST_NAME = 'Taylor'
ORDER BY HIRE_DATE ASC 

SELECT last_name, department_id
FROM EMPLOYEES
WHERE DEPARTMENT_ID = '50'
OR DEPARTMENT_ID = '20'
order BY LAST_NAME ASC

SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary"
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000
AND (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50) 
ORDER BY 2 DESC;

SELECT last_name, HIRE_DATE
FROM EMPLOYEES
WHERE hire_date BETWEEN '01-gen-2005' AND '31-dic-2005'
ORDER BY 1;

SELECT last_name, job_id
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL

SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC, 3 DESC

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE MANAGER_ID = 103
ORDER BY 2

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LOWER(LAST_NAME) LIKE '%a%'
and LOWER(LAST_NAME) LIKE '%e%'

SELECT last_name, job_id, salary
FROM EMPLOYEES
WHERE (JOB_ID = 'SA_REP' OR JOB_ID = 'ST_CLERK')
AND SALARY NOT IN (2500, 3500, 7000)
ORDER BY 3;

SELECT TO_CHAR(SYSDATE) AS "DATE"
FROM DUAL

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, SALARY + TRUNC((SALARY *15.5/100)) AS "NEW SALARY"
FROM EMPLOYEES

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, SALARY + TRUNC((SALARY *15.5/100)) AS "NEW SALARY", TRUNC((SALARY *15.5/100)) AS "INCREASE"
FROM EMPLOYEES

SELECT LAST_NAME AS "NAME", LENGTH(LAST_NAME) AS "LENGTH"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'H%'

SELECT LAST_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS "MONTHS WORKED"
FROM EMPLOYEES
ORDER BY 2 DESC

SELECT LAST_NAME, LPAD(SALARY, 15, '$') AS SALARY
FROM EMPLOYEES

SELECT LAST_NAME, LPAD('*', ROUND(SALARY/1000),'*') AS SALARY_IN_ASTERISK
FROM EMPLOYEES
ORDER BY 2 DESC

SELECT LAST_NAME, TRUNC((SYSDATE - HIRE_DATE)/7) AS "TENURE"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER BY 2 DESC

SELECT (last_name || ' earns' ||TO_CHAR(SALARY, '$99,999') || ' monthly but wants ' || TO_CHAR(SALARY * 3, '$99,999')) AS "DREAM SALARIES"
FROM EMPLOYEES
ORDER BY LAST_NAME

SELECT LAST_NAME, nvl(to_char(commission_pct), 'No Commission') AS COMMISSION_PCT
FROM EMPLOYEES

--FUNZIONI CON LE DATE
SELECT employee_id, hire_date, to_char(hire_date, 'MONTH DD, YYYY')
FROM EMPLOYEES

SELECT TO_CHAR(TO_DATE('05-FEB-2019 19.32.18', 'DD-MON-YYYY HH24:MI:SS'), 'MON')
FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE, 13)
FROM DUAL

SELECT LAST_DAY('01-FEB-2016')
FROM DUAL

SELECT NEXT_DAY('01-GIU-19', 'LUNEDI')
FROM DUAL

SELECT ROUND(TO_DATE('25-OTT-19'), 'YYYY')
FROM DUAL

SELECT LAST_NAME, HIRE_DATE, TO_CHAR((NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'LUNEDI')), 'FMDay ", the "ddspth" OF "Month", "YYYY') AS "REVIEW"
FROM EMPLOYEES

SELECT JOB_ID, max(SALARY) AS "Maximum", min(SALARY) AS "Minimum", sum(SALARY) AS "Sum", ROUND(AVG(SALARY)) AS "Average"
FROM EMPLOYEES
GROUP BY JOB_ID

SELECT job_id, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES
GROUP BY JOB_ID

SELECT count(DISTINCT MANAGER_ID)
FROM EMPLOYEES

SELECT max(SALARY) - min(SALARY) AS "Difference"
FROM EMPLOYEES

SELECT DISTINCT manager_id, min(SALARY)
FROM EMPLOYEES
HAVING min(SALARY) > 6000 AND MANAGER_ID IS NOT null
GROUP BY MANAGER_ID
ORDER BY 2 DESC

SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, country_name
FROM LOCATIONS NATURAL JOIN COUNTRIES 

SELECT e.FIRST_NAME, e.last_name, e.department_id, d.department_name
FROM EMPLOYEES e JOIN DEPARTMENTS d
on(e.DEPARTMENT_ID = d.DEPARTMENT_ID)

SELECT LAST_name, job_id, DEPARTMENT_id, DEPARTMENT_name
FROM EMPLOYEES JOIN DEPARTMENTS
using(DEPARTMENT_id)
JOIN LOCATIONS
using(location_id)
WHERE location_id = '1800'

SELECT emp.FIRST_NAME || ' ' || emp.LAST_NAME AS "Employee", EMP.EMPLOYEE_ID AS "EMP#",
		mng.FIRST_NAME || ' ' || mng.LAST_NAME AS "Manager", MNG.MANAGER_ID AS "MNG#"
FROM EMPLOYEES emp JOIN EMPLOYEES mng
on(emp.MANAGER_ID = mng.EMPLOYEE_ID)
ORDER BY 4 DESC







